//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Content = $ModelResult<$Schema, "Content">;
export type Post = $ModelResult<$Schema, "Post">;
export type Post1 = $ModelResult<$Schema, "Post1">;
export const ContentType = $schema.enums.ContentType.values;
export type ContentType = (typeof ContentType)[keyof typeof ContentType];
